routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Auth::routes();


Route::get('/', 'HomeController@index')->name('home.index_home');

Route::resource('/autores', 'AutoresController');
//aqui abaixo serve para o laravel montar o model de forma correta pois ele singulariza
//o nome do controller de maneira errada em outras linguas
Route::resource('autores', 'AutoresController')->parameters([
    'autores' => 'autor'
]);
Route::resource('editoras', 'EditorasController');
Route::resource('livros', 'LivrosController');



    // ->names(['create' => 'autores.cadastro'], //formulario de cadastro
    //         ['show' => 'autores.lista'], //lista todos
    //         ['destroy' => 'autores.exclui'], //exclui
    //         ['store' => 'autores.salva'], //salva o cadastro
    //         ['update' => 'autores.edita'], //salva a edicao
    //         ['edit' => 'autores.edicao']); //formulario de edicao
Route::resource('contato', 'ContatoController');

// o resources gera isso:
// GET/contacts, mapped to the index() method,
// GET /contacts/create, mapped to the create() method,
// POST /contacts, mapped to the store() method,
// GET /contacts/{contact}, mapped to the show() method,
// GET /contacts/{contact}/edit, mapped to the edit() method,
// PUT/PATCH /contacts/{contact}, mapped to the update() method,
// DELETE /contacts/{contact}, mapped to the destroy() method.

app/Livro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Livro extends Model
{
    	/*
        o laravel sempre procura por padrao nome de
        tabela no banco no plural, mesmo que tenha criado
        no migration no singular, por isso tem de usar
        essa linha abaixo    
        */
        protected $table = 'liv_livros';
        
        /*essas linhas abaixo são para alterar o nome padrão das colunas*/
        const CREATED_AT = 'dt_cadastro';
        const UPDATED_AT = 'dt_alteracao';
    
        /*
        o laravel trabalha com todas colunas primarias sendo id,
        se quiser trocar, tem de usar a variável abaixo
        */
        protected $primaryKey = 'id_livro';
    
        protected $fillable = [
            'titulo','capa','valor','id_autor','id_editora','id_user','f1','f2','f3'
        ];
        /*não são retornados em arrays*/
        
}

app/Http/Controllers/LivrosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Livro;
use App\Autor;
use App\Editora;
use Illuminate\Support\Facades\Storage;
use Auth;



class LivrosController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $livros = Livro::all();
        $livros = DB::table('liv_livros as l')
                     ->join('liv_autores as a', 'l.id_autor','a.id_autor')
                     ->join('liv_editoras as e','e.id_editora', 'l.id_editora')
                     ->join('users as u', 'l.id_user','u.id')
                     ->orderBy('id_livro','desc')                     
                     ->get();
        
        return view('livros.index_livro', compact('livros'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        $livros = Livro::all();
        $editoras = Editora::all();
        $autores = Autor::all();
        return view('livros.cadastro_livro',compact('livros','editoras','autores'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titulo'=>'required',
            'capa'=>'required',
            'valor'=>'required',
            'autor'=>'required',
            'editora'=>'required',
        ]);


        $livros = new livro([
            'titulo' => $request->get('titulo'),
            'capa' => $request->get('capa'),
            'valor' => $request->get('valor'),
            'id_autor' => $request->get('autor'),
            'id_editora' => $request->get('editora'),
            'id_user' => Auth::user()->id
        ]);
        //SALVO SEM CADASTRAS NOMES DAS IMAGENS PARA PODER ADICIONAR SUAS ID´S AO NOME.
        //poderia até gerar um nome randomico, mas acredito que assim fica mais fácil para
        //manusear as imagens

        if($livros->save()){
            $id = $livros->id_livro;//id gerado pelo ultimo save
            $this->envia_arqs($request,$id);
            return redirect('/livros')->with('success', 'Cadastro salvo!');
        }
    }




    public function envia_arqs($request,$id)
    {
        //dd($request);
        //INICIO UPDATE NOME DAS IMAGENS NO BANCO
        for ($i=1; $i < 4; $i++) { //laço para atualizar nome imagens no banco, caso exista
            if($request->hasFile('img'.$i) && $request->file('img'.$i)->isValid()){ // Se informou o arquivo, retorna um boolean
                //$img1 = $request->img1->getClientOriginalName();
                $img['img'.$i] = $id.'_'.$i.'.'.$request->file('img'.$i)->getClientOriginalExtension();
            }else{
                $img['img'.$i] = "";
            }
        }

        $este_livro = livro::find($id);
        $este_livro->f1 = $img['img1'];
        $este_livro->f2 = $img['img2'];
        $este_livro->f3 = $img['img3'];
        $enviou = $este_livro->save();
        //FINAL UPDATE NOME DAS IMAGENS NO BANCO

        for ($i=1; $i < 4; $i++) {
            $arquivo_da_vez = 'img'.$i;

            if($request->hasFile('img'.$i) && $request->file('img'.$i)->isValid()){
                $file = $request->file($arquivo_da_vez);
                $extensao = $request->file($arquivo_da_vez)->getClientOriginalExtension();

                $upload = $request->file($arquivo_da_vez)->storeAs('livros/'.$id, $id.'_'.$i.'.'.$extensao);
            }
        }
    }





    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //$livro = livro::find($id);
        $livro = DB::table('liv_livros as l')
                       ->join('liv_autores as a', 'l.id_autor','a.id_autor')
                       ->join('liv_editoras as e', 'l.id_editora', 'e.id_editora')
                       //->join('users as u', 'l.id_user','u.id')
                       ->where('id_livro',$id)
                       ->get();

        $editoras = Editora::all();
        $autores = Autor::all();
        return view('livros.edit_livro', compact('livro','editoras','autores'));
    }





    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'titulo'=> 'required',
            'capa'=> 'required',
            'valor'=> 'required',
            'editora'=>'required',
            'autor'=> 'required',
        ]);

        $livro = livro::find($id);
        $livro->titulo = $request->get('titulo');
        $livro->capa = $request->get('capa');
        $livro->valor = $request->get('valor');
        $livro->id_editora = $request->get('editora');
        $livro->id_autor = $request->get('autor');
        $livro->id_user = Auth::user()->id;

        if($livro->save()){
            $this->envia_arqs($request,$id);
            return redirect('/livros')->with('success', 'Livro atualizado com sucesso!');
        }

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $livro = livro::find($id);
        $livro->delete();

        return redirect('/livros')->with('success', 'livro '.$livro->livro.' apagado com sucesso!');
    }
}

resources/views/livros/cadastro_livro.blade.php
@extends('layouts.app')

@section('content')


<div class="row">
 <div class="col-sm-8 offset-sm-2  bg-white sombra p-5">
    <h1 class="display-5"><i class="fa fa-book"></i> Cadastro de Livro</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('livros.store') }}" enctype="multipart/form-data">
          @csrf

          <div class="form-group">                  
              <input type="text" class="form-control" name="titulo" required/>
              <div class='text-muted small'>Título</div>
          </div>

          <div class='form-group'>
              <select id='autor' name='autor' class="custom-select" required>
                  <option selected value="">Escolha um autor...</option>                            
                      <?php                        
                          foreach ($autores as $autor) {
                      ?>
                              <option value="<?= $autor->id_autor ?>" >
                                  <?= $autor->autor ?>
                              </option>
                      <?php
                          }
                      ?>
                  </div>
              </select>
              <div class='text-muted small'>Autor</div>
          </div>

          <div class='form-group'>
              <select id='editora' name='editora' class="custom-select" required>
                  <option selected value="">Escolha uma editora...</option>                            
                      <?php
                          foreach ($editoras as $editora) {
                      ?>
                              <option value="<?= $editora->id_editora ?>" >
                                  <?= $editora->editora ?>
                              </option>
                      <?php
                          }
                      ?>
                  </div>
              </select>
              <div class='text-muted small'>Editora</div>
          </div>

          <div class='form-group'>
            <label for='capa'></label>
            <input type='text' id='capa' name='capa' class='form-control'
                 required maxlength='30' >
            <div class='text-muted small'>capa</div>
          </div>

          <div class='form-group'>
            <label for='valor'></label>
            <input type='text' id='valor' name='valor' class='form-control'
                 required maxlength='30' >
            <div class='text-muted small'>valor</div>
          </div>

          <div class="form-group">
              <div class="custom-file">
                  <input type="file" class="custom-file-input" id="img1" name="img1">
                  <label class="custom-file-label" for="img1">Procurar arquivo</label>
              </div>
          </div>

          <div class="form-group">
              <div class="custom-file">
                  <input type="file" class="custom-file-input" id="img2" name="img2">
                  <label class="custom-file-label" for="img2">Procurar arquivo</label>
              </div>
          </div>

          <div class="form-group">
              <div class="custom-file">
                  <input type="file" class="custom-file-input" id="img3" name="img3">
                  <label class="custom-file-label" for="img3">Procurar arquivo</label>
              </div>
          </div>
                                   
          <button type="submit" class="btn btn-success">
            <i class="fa fa-save"></i>
            Salvar Livro
          </button>
      </form>
  </div>
</div>
</div>



<?php
    if($_SERVER['SERVER_NAME'] == 'localhost'){
            //echo _SERVER['SERVER_NAME'];    
    ?>
    <!--  *********************************************** 
    script para testes 
    -->
    <script>
        $(document).ready(function(){
            $('#preenche').on('click',function(e){
                e.preventDefault();
                //var inputs = new Array();            
                $('input').each(function(){            
                    if($(this).attr('name') !== 'csrf_test_name' && $(this).attr('type') !== 'file' && $(this).attr('name') !== '_token'){
                    //inputs.push($(this).val());
                    min = Math.ceil(0);
                    max = Math.floor(99);
                    $("input[name="+$(this).attr('name')+"]").val($(this).attr('name')+'_'+Math.floor(Math.random() * (max - min)));
                    }
                });
                //$('input[type=text]').val($(this).attr('name')); //deixa todos iguais
                $('input[type=date]').val('1985-12-06');
                $('input[type=email]').val('teste@teste.com');
                $('input[type=number]').val(123);
                //$('option[value=MG]').attr('selected','selected');
                $("select").prop("selectedIndex", 2);
                $('input[type=checkbox]').attr('checked','checked');
                $('textarea').each(function(){
                   if($(this).attr('name') !== 'csrf_test_name' && $(this).attr('type') !== 'file'){
                   //inputs.push($(this).val());
                   $("textarea[name="+$(this).attr('name')+"]").val($(this).attr('name'));
                   }
               });
            });
        });
    </script>

    <div class='container bg-white text-center'>
        <a href="#" id="preenche" class="btn btn-success">
            <span class="fa fa-plus"></span>
            Preencher inputs
        </a>
    </div>
    <!--  *********************************************** 
        script para testes 
    -->
    <?php
    }
?>

@endsection

resources/views/livros/edit_livro.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2 bg-white sombra p-5">
        <h1 class="display-5">Edição de livro</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('livros.update', $livro[0]->id_livro) }}" enctype="multipart/form-data">
            @method('PATCH') 
            @csrf

            ID {{ $livro[0]->id_livro }}

            <div class="form-group">                  
                <input type="text" class="form-control" name="titulo" value="{{$livro[0]->titulo}}"/>
                <div class='text-muted small'>Título</div>
            </div>
    
            <div class='form-group'>
                <select id='autor' name='autor' class="custom-select" >
                <option selected value="{{$livro[0]->id_autor}}">{{$livro[0]->autor}}</option>                            
                        <?php                        
                            foreach ($autores as $autor) {
                        ?>
                                <option value="<?= $autor->id_autor ?>" >
                                    <?= $autor->autor ?>
                                </option>
                        <?php
                            }
                        ?>
                    </div>
                </select>
                <div class='text-muted small'>Autor</div>
            </div>
    
            <div class='form-group'>
                <select id='editora' name='editora' class="custom-select" >
                        <option selected value="{{$livro[0]->id_editora}}">{{$livro[0]->editora}}</option>                            
                        <?php
                            foreach ($editoras as $editora) {
                        ?>
                                <option value="<?= $editora->id_editora ?>" >
                                    <?= $editora->editora ?>
                                </option>
                        <?php
                            }
                        ?>
                    </div>
                </select>
                <div class='text-muted small'>Editora</div>
            </div>
    
            <div class='form-group'>
                <label for='capa'></label>
                <input type='text' id='capa' name='capa' class='form-control' value="{{$livro[0]->capa}}"
                    required maxlength='30' >
                <div class='text-muted small'>Capa</div>
            </div>
    
            <div class='form-group'>
                <label for='valor'></label>
                <input type='text' id='valor' name='valor' class='form-control' value="{{$livro[0]->valor}}"
                    required maxlength='30' >
                <div class='text-muted small'>Valor</div>
            </div>

            <div class="form-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="img1" name="img1">
                    <label class="custom-file-label" for="img1">Procurar arquivo</label>
                </div>
            </div>

            <div class="form-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="img2" name="img2">
                    <label class="custom-file-label" for="img2">Procurar arquivo</label>
                </div>
            </div>

            <div class="form-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="img3" name="img3">
                    <label class="custom-file-label" for="img3">Procurar arquivo</label>
                </div>
            </div>  

            <div class="row">

                <div class="col-sm-4">
                    <img src="{{ url('storage/livros/'.$livro[0]->id_livro.'/'.$livro[0]->f1) }}" alt=""
                      title='' class='img-fluid rounded'>
                      <div class='text-muted small'>Imagem 1</div>
                </div>

                <div class="col-sm-4">
                    <img src="{{ url('storage/livros/'.$livro[0]->id_livro.'/'.$livro[0]->f2) }}" alt=""
                        title='' class='img-fluid rounded'>
                        <div class='text-muted small'>Imagem 2</div>
                </div>

                <div class="col-sm-4">
                    <img src="{{ url('storage/livros/'.$livro[0]->id_livro.'/'.$livro[0]->f3) }}" alt=""
                        title='' class='img-fluid rounded'>
                        <div class='text-muted small'>Imagem 3</div>
                </div>
            </div>

            <button type="submit" class="btn btn-success">
                <i class="fa fa-save"></i>
                Atualiza
            </button>
            <a href="{{ route('livros.index') }} " class='btn btn-secondary'>
                <span class="fa fa-arrow-circle-left"></span>
                Voltar
            </a>
            
        </form>
    </div>
</div>
@endsection

resources/views/livros/index_livro.blade.php
@extends('layouts.app')

@section('content')

    <div class="row bg-white sombra p-5">
        <div class="col-12 text-center">
            <a href="{{ route('home.index_home') }}" class='btn btn-primary'>
                <span class="fa fa-home"></span>
                Home
            </a>
            <a href="{{ route('livros.create') }}" class='btn btn-warning'>
                <span class="fa fa-plus"></span>
                Cadastro de Livros
            </a>
        </div>

        <div class="col-6 offset-3 text-center mt-3">
            @if(session()->get('success'))
                <div class="alert alert-success">
                {{ session()->get('success') }}
                </div>
            @endif


            @if ($errors->any())
                <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
                </div><br />
            @endif
        </div>

        <div class="col-sm-12">
            <h1 class="display-3">Livros</h1> <p class="text-muted">Exibição mais recente/primeiro</p>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                        <td>ID</td>
                        <td>Nome do livro</td>
                        <td>Capa</td>
                        <td>Valor</td>
                        <td>Editora</td>
                        <td>Autor</td>
                        <td>Última Alteração</td>
                        <td colspan = 2>Ações</td>
                        </tr>
                    </thead>
                    <tbody>                        
                        @foreach($livros as $livro)
                        <tr>
                            <td>{{$livro->id_livro}}</td>
                            <td>{{$livro->titulo}} </td>
                            <td>{{$livro->autor}}</td>
                            <td>{{$livro->editora}}</td>
                            <td>{{$livro->capa}}</td>
                            <td>{{$livro->valor}}</td>
                            <td>{{$livro->name}} </td>
                            <td>
                                <a href="{{ route('livros.edit',$livro->id_livro)}}" class="btn btn-success">Editar</a>
                            </td>
                            <td>
                                <form action="{{ route('livros.destroy', $livro->id_livro)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" onclick="return confirm('Tem certeza');" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection