routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Auth::routes();


Route::get('/', 'HomeController@index')->name('home.index_home');

Route::resource('/autores', 'AutoresController');
//aqui abaixo serve para o laravel montar o model de forma correta pois ele singulariza
//o nome do controller de maneira errada em outras linguas
Route::resource('autores', 'AutoresController')->parameters([
    'autores' => 'autor'
]);
Route::resource('editoras', 'EditorasController');
Route::resource('livros', 'LivrosController');



    // ->names(['create' => 'autores.cadastro'], //formulario de cadastro
    //         ['show' => 'autores.lista'], //lista todos
    //         ['destroy' => 'autores.exclui'], //exclui
    //         ['store' => 'autores.salva'], //salva o cadastro
    //         ['update' => 'autores.edita'], //salva a edicao
    //         ['edit' => 'autores.edicao']); //formulario de edicao
Route::resource('contato', 'ContatoController');

// o resources gera isso:
// GET/contacts, mapped to the index() method,
// GET /contacts/create, mapped to the create() method,
// POST /contacts, mapped to the store() method,
// GET /contacts/{contact}, mapped to the show() method,
// GET /contacts/{contact}/edit, mapped to the edit() method,
// PUT/PATCH /contacts/{contact}, mapped to the update() method,
// DELETE /contacts/{contact}, mapped to the destroy() method.

app/Http/Controllers/AutoresController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Autor;
use Auth;
use DB;


class AutoresController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$autores = Autor::all();
        $autores = DB::table('liv_autores as a')
                       ->join('users as u', 'a.id_user','u.id')                       
                       ->get();   
        
        return view('autores.index_autor', compact('autores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('autores.cadastro_autor');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'autor'=>'required'
        ]);

        $autores = new Autor([
            'autor' => $request->get('autor'),
            'id_user' => Auth::user()->id
        ]);
        $autores->save();
        return redirect('/autores')->with('success', 'Cadastro salvo!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $autores = Autor::find($id);
        // $autores = DB::table('liv_autores as a')
        //                ->join('users as u', 'a.id_user','u.id')                       
        //                ->get();        
        
        return view('autores.edit_autor', compact('autores'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'autor'=>'required'
        ]);

        $autor = Autor::find($id);
        $autor->autor = $request->get('autor');
        $autor->id_user = Auth::user()->id;
        $autor->save();

        return redirect('/autores')->with('success', 'Autor atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $autor = Autor::find($id);
        $autor->delete();

        return redirect('/autores')->with('success', 'Autor '.$autor->autor.' apagado com sucesso!');
    }
}

resources/views/autores/cadastro_autor.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2 bg-white sombra p-5">
    <h1 class="display-5"><i class="fa fa-superpowers"></i> Cadastro de Autor</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('autores.store') }}">
          @csrf
          <div class="form-group">    
              <label for="autor">Autor</label>
              <input type="text" class="form-control" name="autor"/>
          </div>

                                   
          <button type="submit" class="btn btn-success">
            <i class="fa fa-save"></i>
            Salvar Autor
          </button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/autores/edit_autor.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2 bg-white sombra p-5">
        <h1 class="display-5">Edição de Autor</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('autores.update', $autores->id_autor) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="autor">Nome do Autor:</label>
                <input type="text" class="form-control" name="autor" value="{{ $autores->autor }}" />
            </div>

            
            <button type="submit" class="btn btn-success">
                <i class="fa fa-save"></i>
                Atualiza
            </button>

            <a href="{{ route('autores.index') }} " class='btn btn-secondary'>
                <span class="fa fa-arrow-circle-left"></span>
                Voltar
            </a>
        </form>
    </div>
</div>
@endsection

resources/views/autores/index_autor.blade.php
@extends('layouts.app')

@section('content')

    <div class="row bg-white sombra p-5">

        <div class="col-12 text-center">
            <a href="{{ route('home') }}" class='btn btn-primary'>
                <span class="fa fa-home"></span>
                Home
            </a>
            <a href="{{ route('autores.create') }}" class='btn btn-warning'>
                <span class="fa fa-plus"></span>
                Cadastro de Autores
            </a>
        </div>

        <div class="col-6 offset-3 text-center mt-3">
            @if(session()->get('success'))
                <div class="alert alert-success">
                {{ session()->get('success') }}
                </div>
            @endif


            @if ($errors->any())
                <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
                </div><br />
            @endif
        </div>

        <div class="col-sm-12">
            <h1 class="display-3">Autores</h1>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                        <td>ID</td>
                        <td>Nome do Autor</td>
                        <td>Última Alteração</td>
                        <td colspan = 2>Ações</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($autores as $autor)
                        <tr>
                            <td>{{$autor->id_autor}}</td>
                            <td>{{$autor->autor}} </td>
                            <td>{{$autor->name}} </td>
                            <td>
                                <a href="{{ route('autores.edit',$autor->id_autor)}}" class="btn btn-success">Editar</a>
                            </td>
                            <td>
                                <form action="{{ route('autores.destroy', $autor->id_autor)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" onclick="return confirm('Tem certeza');" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection