routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Auth::routes();


Route::get('/', 'HomeController@index')->name('home.index_home');

Route::resource('/autores', 'AutoresController');
//aqui abaixo serve para o laravel montar o model de forma correta pois ele singulariza
//o nome do controller de maneira errada em outras linguas
Route::resource('autores', 'AutoresController')->parameters([
    'autores' => 'autor'
]);
Route::resource('editoras', 'EditorasController');
Route::resource('livros', 'LivrosController');



    // ->names(['create' => 'autores.cadastro'], //formulario de cadastro
    //         ['show' => 'autores.lista'], //lista todos
    //         ['destroy' => 'autores.exclui'], //exclui
    //         ['store' => 'autores.salva'], //salva o cadastro
    //         ['update' => 'autores.edita'], //salva a edicao
    //         ['edit' => 'autores.edicao']); //formulario de edicao
Route::resource('contato', 'ContatoController');

// o resources gera isso:
// GET/contacts, mapped to the index() method,
// GET /contacts/create, mapped to the create() method,
// POST /contacts, mapped to the store() method,
// GET /contacts/{contact}, mapped to the show() method,
// GET /contacts/{contact}/edit, mapped to the edit() method,
// PUT/PATCH /contacts/{contact}, mapped to the update() method,
// DELETE /contacts/{contact}, mapped to the destroy() method.

app/Editora.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Editora extends Model
{
    	/*
        o laravel sempre procura por padrao nome de
        tabela no banco no plural, mesmo que tenha criado
        no migration no singular, por isso tem de usar
        essa linha abaixo    
        */
        protected $table = 'liv_editoras';
        
        const CREATED_AT = 'dt_cadastro';
        const UPDATED_AT = 'dt_alteracao';
    
        /*
        o laravel trabalha com todas colunas primarias sendo id,
        se quiser trocar, tem de usar a variável abaixo
        */
        protected $primaryKey = 'id_editora';
    
        protected $fillable = [
            'editora','id_user'
        ];        
}

app/Http/Controllers/EditorasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Editora;
use Auth;
use DB;

class EditorasController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$editoras = Editora::all();
        $editoras = DB::table('liv_editoras as e')
                       ->join('users as u', 'e.id_user','u.id')                       
                       ->get();
                       
        return view('editoras.index_editora', compact('editoras'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('editoras.cadastro_editora');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'editora'=>'required'
        ]);

        $editora = new editora([
            'editora' => $request->get('editora'),
            'id_user' => Auth::user()->id
        ]);
        $editora->save();
        return redirect('/editoras')->with('success', 'Cadastro salvo!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editoras = editora::find($id);
        
        return view('editoras.edit_editora', compact('editoras'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'editora'=>'required'
        ]);

        $editora = editora::find($id);
        $editora->editora = $request->get('editora');
        $editora->id_user = Auth::user()->id;
        
        $editora->save();

        return redirect('/editoras')->with('success', 'Editora atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $editora = editora::find($id);
        $editora->delete();

        return redirect('/editoras')->with('success', 'editora '.$editora->editora.' apagado com sucesso!');
    }
}

resources/views/editoras/cadastro_editora.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2 bg-white sombra p-5">
    <h1 class="display-5">Cadastro de Editora</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('editoras.store') }}">
          @csrf
          <div class="form-group">                  
              <input type="text" class="form-control" name="editora"/>
              <div class='text-muted small'>Nome</div>
          </div>

                                   
          <button type="submit" class="btn btn-success">
            <i class="fa fa-save"></i>
            Salvar Editora
          </button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/editoras/edit_editora.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2 bg-white sombra p-5">
        <h1 class="display-5">Edição de editora</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('editoras.update', $editoras->id_editora) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="editora">Nome do editora:</label>
                <input type="text" class="form-control" name="editora" value="{{ $editoras->editora }}" />
            </div>

            
            <button type="submit" class="btn btn-success">
                <i class="fa fa-save"></i>
                Atualiza
            </button>

            <a href="{{ route('editoras.index') }} " class='btn btn-secondary'>
                <span class="fa fa-arrow-circle-left"></span>
                Voltar
            </a>
        </form>
    </div>
</div>
@endsection

resources/views/editoras/index_editora.blade.php
@extends('layouts.app')

@section('content')



    <div class="row bg-white sombra p-5">

        <div class="col-12 text-center">
            <a href="{{ route('home') }}" class='btn btn-primary'>
                <span class="fa fa-home"></span>
                Home
            </a>
            <a href="{{ route('editoras.create') }}" class='btn btn-warning'>
                <span class="fa fa-plus"></span>
                Cadastro de Editoras
            </a>
        </div>

        <div class="col-6 offset-3 text-center mt-3">
            @if(session()->get('success'))
                <div class="alert alert-success">
                {{ session()->get('success') }}
                </div>
            @endif


            @if ($errors->any())
                <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
                </div><br />
            @endif
        </div>

        <div class="col-sm-12">
            <h1 class="display-3">Editoras</h1>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                        <td>ID</td>
                        <td>Nome do editora</td>
                        <td>Última Alteração</td>
                        <td colspan = 2>Ações</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($editoras as $editora)
                        <tr>
                            <td>{{$editora->id_editora}}</td>
                            <td>{{$editora->editora}}</td>
                            <td>{{$editora->name}} </td>
                            <td>
                                <a href="{{ route('editoras.edit',$editora->id_editora)}}" class="btn btn-success">Editar</a>
                            </td>
                            <td>
                                <form action="{{ route('editoras.destroy', $editora->id_editora)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" onclick="return confirm('Tem certeza');" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection