routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Auth::routes();


Route::get('/', 'HomeController@index')->name('home.index_home');

Route::resource('/autores', 'AutoresController');
//aqui abaixo serve para o laravel montar o model de forma correta pois ele singulariza
//o nome do controller de maneira errada em outras linguas
Route::resource('autores', 'AutoresController')->parameters([
    'autores' => 'autor'
]);
Route::resource('editoras', 'EditorasController');
Route::resource('livros', 'LivrosController');



    // ->names(['create' => 'autores.cadastro'], //formulario de cadastro
    //         ['show' => 'autores.lista'], //lista todos
    //         ['destroy' => 'autores.exclui'], //exclui
    //         ['store' => 'autores.salva'], //salva o cadastro
    //         ['update' => 'autores.edita'], //salva a edicao
    //         ['edit' => 'autores.edicao']); //formulario de edicao
Route::resource('contato', 'ContatoController');

// o resources gera isso:
// GET/contacts, mapped to the index() method,
// GET /contacts/create, mapped to the create() method,
// POST /contacts, mapped to the store() method,
// GET /contacts/{contact}, mapped to the show() method,
// GET /contacts/{contact}/edit, mapped to the edit() method,
// PUT/PATCH /contacts/{contact}, mapped to the update() method,
// DELETE /contacts/{contact}, mapped to the destroy() method.

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    @include('layouts.cabecalho')

    <body>
        <div id="app">

            @include('layouts.menu')

            <main class="container py-50">
                @yield('content')
            </main>
        </div>
    </body>
</html>

resources/views/layouts/cabecalho.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="pt-br">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="desenvolvimento de sites, criação de sites, sites Sul de Minas, Programador, preço de site, contratar desenvolvedor, Poços de Caldas, Alfenas, Varginha">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Luiz Eduardo">

    <?php
        if(isset($detalhes->tag_title)){
    ?>
        <title><?= $detalhes->tag_title  ?> | Portfolio Luiz Eduardo - Via de Regra</title>
        <meta name="title" content ="<?= $detalhes->tag_title  ?> | Portfolio Luiz Eduardo - Via de Regra" >
        <?php /*<meta name="description" CONTENT="<?= substr($detalhes->secao,0,152) ?>">*/ ?>
        <meta name="description" CONTENT="<?= $detalhes->tag_description ?>">
        <meta property="og:title"         content="<?= $detalhes->tag_title ?> | Portfolio Luiz Eduardo - Via de Regra" />
        <?php /*<meta property="og:description"   content="<?= substr($detalhes->secao,0,152) ?>" />*/ ?>
        <meta property="og:description"   content="<?= $detalhes->tag_description ?>" />
    <?php
        }else{
    ?>
        <title>Portfolio Luiz Eduardo - Desenvolvedor</title>
        <meta name="title" content ="Portfolio Luiz Eduardo - Desenvolvimento de sites para Minas e Brasil" >
        <meta name="description" CONTENT="Portfolio Luiz Eduardo - Desenvolvimento de site responsivo, site bonito, com otimização de SEO e Marketing Digital por preço justo.">
        <meta property="og:title"         content="Portfolio Luiz Eduardo - Desenvolvimento de sites para Minas e Brasil" />
        <meta property="og:description"   content="Portfolio Luiz Eduardo - Desenvolvimento de site responsivo, site bonito, com otimização de SEO e Marketing Digital por preço justo." />
    <?php
        }    
        if(isset($_SESSION['codigo'])){ 
        //se estiver logado nao deve ser indexado nem seguido
    ?>
        <meta name="robots" content="noindex, nofollow">
    <?php
        }else{
    ?>
        <meta name="robots" content="index, follow">
    <?php
        }
    ?>

    <link rel="amphtml" href="https://www.viaderegra.com.br/">
    <link rel="dns-prefetch" href="https://www.viaderegra.com">
    <link rel="dns-prefetch" href="https://www.viaderegra.com.br">
    <link rel="dns-prefetch" href="https://www.manualdoesperto.com">
    <link rel="dns-prefetch" href="https://www.manualdoesperto.com.br">        
    <link rel='dns-prefetch' href='https://www.facebook.com/luizeduardots' />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/jquery.min.js') }}" ></script>    
    <script src="{{ asset('js/holder.min.js') }}" ></script>    

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link href="{{ asset('css/margens.css') }}" rel="stylesheet">
    <link href="{{ asset('css/cores.css') }}" rel="stylesheet">
    <link href="{{ asset('css/mediaqueries.css') }}" rel="stylesheet">
    <link href="{{ asset('css/backgrounds.css') }}" rel="stylesheet">
    <link href="{{ asset('css/fontes.css') }}" rel="stylesheet">
    <link href="{{ asset('css/diversos.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
</head>

resources/views/layouts/menu.blade.php
<script>
    $(document).ready(function(){
        $('li a').click(function (e) {
            //alert($(this).attr('href'));
            if($(this).attr('href')=='#livros'){
                e.preventDefault();

                $('html,body').animate({
                    scrollTop: $(this).offset().top +250
                }, 1000);
            }
        });
    });
</script>




    @unless (Auth::check()) {{-- so mostra se não estiver logado --}}
        <div class="parallax py-150" >
            <div class="col-6 offset-6 bg-translucido text-white negrito p-3 text-right rounded montserrat" >
                <h2>Livraria Laravel</h2>
                <h4>Venha mergulhar no mundo da leitura!</h4>
            </div>
        </div>
    @endunless

    <nav class="navbar navbar-expand-md navbar-dark bg-azul shadow-sm sticky-top" >
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                <img src="{{ url('/storage/lara.png') }}" width="40" height="40" alt="">
                <i class="fa fa-home"></i>{{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if(\Request::is('/') || \Request::is('/#livros') )
                            <li class="nav-item">
                                <a class="nav-link active" href="#livros">Nossos Livros</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link active" href="{{ url('/#livros') }}">Nossos Livros</a>
                            </li>
                        @endif
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link active" href="{{ route('register') }}">{{ __('Cadastre-se') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown active">
                            <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-book"></i>Livros
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('livros.index') }}"><i class="fa fa-list"></i>Lista</a>
                            <a class="dropdown-item" href="<?= route('livros.create'); ?>"><i class="fa fa-user-plus"></i> Cadastro de Livros</a>

                            </div>
                        </li>

                        <li class="nav-item dropdown active">
                            <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-superpowers"></i>Autores
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('autores.index') }}"><i class="fa fa-list"></i>Lista</a>
                            <a class="dropdown-item" href="<?= route('autores.create'); ?>"><i class="fa fa-user-plus"></i> Cadastro de Autores</a>

                            </div>
                        </li>

                        <li class="nav-item dropdown active">
                            <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-users"></i>Editoras
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('editoras.index') }}"><i class="fa fa-list"></i>Lista</a>
                            <a class="dropdown-item" href="<?= route('editoras.create'); ?>"><i class="fa fa-user-plus"></i> Cadastro de Editoras</a>

                            </div>
                        </li>



                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

resources/views/layouts/menu_admin.blade.php
<?php
  defined('BASEPATH') OR exit('No direct script access allowed');
?>

    
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-verde py-3 mb-5">
  
  <a class="navbar-brand" href="<?= base_url(); ?>">
    <img src="<?= base_url('img/icones/logo.jpg'); ?>" alt="Livraria Babilônia"
        title='Livraria Babilônia' class='rounded' width='50px'>
    Livraria Babilônia
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto sem-sub-branco">

      <li class="nav-item active">
        <a class="nav-link" href="<?= base_url('livros/lista'); ?>"><i class="fa fa-book"></i> Livros</a>
      </li>
      
      <li class="nav-item active">
        <a class="nav-link" href="<?= base_url('autores/lista'); ?>"><i class="fa fa-users"></i> Autores</a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="<?= base_url('editoras/lista'); ?>"><i class="fa fa-list"></i> Editoras</a>
      </li>

            
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user-plus"></i>Usuários
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<?= base_url('login'); ?>"><i class="fa fa-user-secret"></i>Login</a>
          <a class="dropdown-item" href="<?= base_url('usuarios'); ?>"><i class="fa fa-user"></i> Lista de Usuários</a>
          <?php          
            if($_SERVER['HTTP_HOST'] == 'localhost'){            
          ?>
          <a class="dropdown-item" href="<?= base_url('usuarios/novo'); ?>"><i class="fa fa-plus"></i>Cadastre-se</a>          
          <?php
            }
          ?>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="<?= base_url('login/sair'); ?>">Sair &nbsp;<i class="fa fa-sign-out"></i></a>
      </li>
      
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Procurar" aria-label="Procurar">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Procurar</button>
    </form> -->
  </div>
</nav>

resources/views/layouts/menu_index.blade.php
<?php
  defined('BASEPATH') OR exit('No direct script access allowed');
?>

    
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-verde py-3 mb-5">
  
  <a class="navbar-brand" href="<?= base_url(); ?>">
    <img src="<?= base_url('img/icones/logo.jpg'); ?>" alt="Livraria Babilônia"
        title='Livraria Babilônia' class='rounded' width='50px'>
        Livraria Babilônia
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto sem-sub-branco">

      <li class="nav-item active">
        <a class="nav-link" href="<?= base_url('livros/lista'); ?>"><i class="fa fa-book"></i>Livros</a>
      </li>
      
      <li class="nav-item active">
        <a class="nav-link" href="<?= base_url('autores/lista'); ?>"><i class="fa fa-users"></i>Autores</a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="<?= base_url('editoras/lista'); ?>"><i class="fa fa-list"></i>Editoras</a>
      </li>

            
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user-plus"></i>Usuários
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<?= base_url('login'); ?>">Login</a>
          <?php          
            if($_SERVER['HTTP_HOST'] == 'localhost'){            
          ?>
          <a class="dropdown-item" href="<?= base_url('usuarios/novo'); ?>">Cadastre-se</a>          
          <?php
            }
          ?>
        </div>
      </li>
      
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Procurar" aria-label="Procurar">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Procurar</button>
    </form> -->
  </div>
</nav>